-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.936 s <<< FAILURE! -- in TestSuite
Runner.TestNgtestRunner.runScenario["Verify if place is successfully added into the AddPlaceAPI", "Validate Add Place Api's"](1) -- Time elapsed: 4.617 s <<< FAILURE!
java.lang.AssertionError: expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertEqualsImpl(Assert.java:150)
	at org.testng.Assert.assertEquals(Assert.java:132)
	at org.testng.Assert.assertEquals(Assert.java:1419)
	at org.testng.Assert.assertEquals(Assert.java:1383)
	at org.testng.Assert.assertEquals(Assert.java:1429)
	at StepDefinitions.stepdefAddplace.validate_api_call_is_success_status_code_is(stepdefAddplace.java:69)
	at âœ½.validate Api call is success status code is 200(file:///C:/Users/VPAVAN/ec1/Bdd2/src/test/java/feature/placevalidations.feature:18)

